### ISSUE TITLE
Build targets file contains invalid command in ClearautoDictionariesAssets

### ISSUE THREAD

**Issue by ronaldbarendse** [Lantzify/auto-dictionaries#15]
**Describe the bug**
After installing this package, doing a Clean causes an error because the targets file seems to contain an invalid command (`<ReautoDir Directories="@(autoDictionariesDir)"  />`, which should be `<RemoveDir />`).

**To Reproduce**
1. Clean project/solution with AutoDictionaries installed

**Expected behavior**
No error when doing a Clean and the App_Plugins files being removed.

**Additional context**
Although I see the build target files are included in the project file, I can't find them in the repository:
https://github.com/Lantzify/auto-dictionaries/blob/b34ae0017f668b2e8b62999d29b5288f8726598d/src/AutoDictionaries/AutoDictionaries.csproj#L39-L43

However, you can inspect the contents of this file and spot the above typo if you open the NuGet file (or go to https://nuget.info/packages/AutoDictionaries/10.0.1).

**Comment by Lantzify** [comment]
Thank you for bringing this to my attention @ronaldbarendse! I am going to change the way that I embed the files. And it will hopefully be done Thursday evening!

**Comment by Lantzify** [comment]
Fixed in 10.0.3
